
version: "3.4"
networks:
  proxylampy:
    external: true
services:
  www:
    image: node:17.4.0
    working_dir: /app
    command: >
      sh -c "npm run start"
    volumes:
      - ${PWD}/apps:/app
    networks:
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.expressjs.rule=Host(`expressjs.traefik.me`)"
        - "traefik.http.routers.expressjs-tls.tls.domains[0].main=expressjs.traefik.me"
        - "traefik.http.routers.expressjs.tls=true"
        - "traefik.http.services.expressjs.loadbalancer.server.port=3000"
