
version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  www:
    image: koromerzhin/nodejs:15.1.0-express
    volumes:
      - ${PWD}/app:/app
    networks:
      - proxynetwork
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.expressjs.rule=Host(`expressjs.traefik.me`)"
        - "traefik.http.routers.expressjs-tls.tls.domains[0].main=expressjs.traefik.me"
        - "traefik.http.routers.expressjs-tls.tls.domains[0].sans=expressjs-*.traefik.me"
        - "traefik.http.services.expressjs.loadbalancer.server.port=3000"